// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package main

import "github.com/DGuang21/goMigration/migration"

func init() {
	migration.RegisterSqlDrive(nil)
}

/**
 * @Description: Run all pending migration files
 * @Description: 运行所有尚未完成的迁移文件
 * @param force
 * @auth: daguang
 */
func Migrate(force ...bool) {
	migration.Migrate(force...)
}

/**
 * @Description:
 * @param step
 * @auth: daguang
 */
func RollBack(step ...int) {
	migration.RollBack(step...)
}

func RollBackAndMigrate(step ...int) {
	migration.RollBack(step...)
}

func Fresh() {
	migration.Fresh()
}